# Generated by Django 5.2 on 2025-04-23 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='weight',
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='PortfolioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=4, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='assets.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'asset')},
            },
        ),
    ]
